language: android
addons:
  sonarcloud:
    organization: "brunamlzupper"
    token: $sonarToken
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.3

android:
  components:
    - tools
    - tools # Running this twice get's the latest build tools
    - platform-tools
    - android-${ANDROID_API}
    - build-tools-${ANDROID_BUILD_TOOLS}
    - extra
script: ./gradlew sonarqube -Dsonar.projectKey=brunamlzupper_MovieApp -Dsonar.organization=brunamlzupper -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=c88b14e3c8c2d5960633ec8a84128599155147af
before_install:
  - chmod +x gradlew
