language: android
addons:
  sonarcloud:
    organization: "brunamlzupper"
    token: $sonarToken
script: sonar:sonar -Pcoverage -Dsonar.projectKey=brunamlzupper_MovieApp
before_install:
  - chmod +x gradlew
